/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wslf.homemoviebase.forms;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import wslf.homemoviebase.logic.Worker;

/**
 *
 * @author Wasyl
 */
public class MainForm extends javax.swing.JFrame {

    Worker worker;

    /**
     * Creates new form MainForm
     */
    public MainForm(Worker worker) {
        this.worker = worker;

        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        rootPathText.setEditable(false);
        if (worker.findRootPath()) {
            rootPathText.setText(worker.getRootFolder());
        } else {
            JOptionPane.showMessageDialog(this, "Корневая папка не найдена", "Ошибка!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEventButton = new javax.swing.JButton();
        rootPathLabel = new javax.swing.JLabel();
        rootPathText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addEventButton.setText("Добавить событие");
        addEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventButtonActionPerformed(evt);
            }
        });

        rootPathLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rootPathLabel.setText(" Корневая папка: ");
        rootPathLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rootPathLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rootPathLabelMouseClicked(evt);
            }
        });

        rootPathText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rootPathText.setText("E:\\TEST_HMV\\E");
        rootPathText.setMargin(new java.awt.Insets(1, 10, 1, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rootPathLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(rootPathText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(addEventButton)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rootPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rootPathText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addEventButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventButtonActionPerformed

        AddEventForm addEventForm = new AddEventForm(worker);
        addEventForm.setVisible(true);
        addEventForm.setAlwaysOnTop(false);
    }//GEN-LAST:event_addEventButtonActionPerformed

    private void rootPathLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootPathLabelMouseClicked

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Выберите корневую папку");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().toString();
            worker.setRootFolder(path);
            rootPathText.setText(path);
        } else {
            System.out.println("No Selection ");
        }


    }//GEN-LAST:event_rootPathLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEventButton;
    private javax.swing.JLabel rootPathLabel;
    private javax.swing.JTextField rootPathText;
    // End of variables declaration//GEN-END:variables
}
