package wslf.homemoviebase.forms;

import java.awt.Font;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Wsl_F
 */
public class ShowDuplicatesForm extends javax.swing.JFrame {

    /**
     * Creates new form showDublicatsForm
     */
    public ShowDuplicatesForm() {
        initComponents();
        setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        duplicatesTable.getTableHeader().setFont(new Font("Times New Roman",
                Font.BOLD, 18));
        duplicatesFoldersText.setText("");
        duplicatesFoldersText.setEditable(false);
        setTitle("Дубликаты!");
    }

    void addDuplicates(List<Pair<String, String>> duplicates) {
        Set<String> folders = new TreeSet<>();
        DefaultTableModel model = (DefaultTableModel) duplicatesTable.getModel();
        model.setRowCount(0);
        for (Pair<String, String> duplicat : duplicates) {
            model.addRow(new Object[]{duplicat.getKey(), duplicat.getValue()});
            String folderName = duplicat.getValue();
            folderName = folderName.substring(0, folderName.lastIndexOf('\\'));
            folderName = folderName.substring(folderName.lastIndexOf('\\') + 1);
            folders.add(folderName);
        }

        StringBuilder allFolders = new StringBuilder("");
        for (String folder : folders) {
            allFolders.append(", ").append(folder);
        }
        duplicatesFoldersText.setText(allFolders.substring(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        duplicatesFoldersText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        duplicatesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Дубликаты в: ");

        duplicatesFoldersText.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        duplicatesFoldersText.setText("jTextField1");

        duplicatesTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        duplicatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Новый файл", "Файл в базе"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        duplicatesTable.setRowHeight(20);
        duplicatesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duplicatesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(duplicatesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(duplicatesFoldersText)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(duplicatesFoldersText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duplicatesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duplicatesTableMouseClicked

        if (evt.getClickCount() == 2) {
            int row = duplicatesTable.getSelectedRow();
            String path = duplicatesTable.getValueAt(row, 1).toString();
            Helper.openPathInExplorer(Paths.get(path), this);
        }
    }//GEN-LAST:event_duplicatesTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duplicatesFoldersText;
    private javax.swing.JTable duplicatesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
